/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\muros.glb --transform --draco 
Files: .\muros.glb [99.85MB] > C:\Users\UsX\Documents\React_templates\arqui-project\public\models\cafeteria\muros-transformed.glb [1.33MB] (99%)
*/

import { useGLTF } from "@react-three/drei";
import * as THREE from "three";

const path = "/models";

export function Muros() {
  const { nodes, materials } = useGLTF(`${path}/cafeteria/muros.glb`);
  return (
    <group dispose={null}>
      <group position={[7.975, 0.041, -14.62]} rotation={[0, Math.PI / 2, 0]}>
        <mesh
          geometry={(nodes.Cube021 as THREE.Mesh).geometry}
          material={materials["mosaico cocina.001"]}
        />
        <mesh
          geometry={(nodes.Cube021 as THREE.Mesh).geometry}
          material={materials["estuco blanco.001"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload(`${path}/cafeteria/muros.glb`);
