/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\terraza-piso.glb --transform --draco 
Files: .\terraza-piso.glb [94.02MB] > C:\Users\UsX\Documents\React_templates\arqui-project\public\models\cafeteria\terraza-piso-transformed.glb [1.69MB] (98%)
*/

import { useGLTF } from "@react-three/drei";
import * as THREE from "three";

const path = "../../../../public/models";

export function TerrazaPiso() {
  const { nodes, materials } = useGLTF(
    `${path}/cafeteria/terraza-piso-transformed.glb`,
  );
  return (
    <group dispose={null}>
      <group position={[2.66, -0.995, -18.75]}>
        <mesh
          geometry={(nodes.Cube022 as THREE.Mesh).geometry}
          material={materials["estuco blanco"]}
        />
        <mesh
          geometry={(nodes.Cube022_1 as THREE.Mesh).geometry}
          material={materials["concreto deslavado"]}
        />
        <mesh
          geometry={(nodes.Cube022_2 as THREE.Mesh).geometry}
          material={materials["concreto deslavado 2"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload(`${path}/cafeteria/terraza-piso-transformed.glb`);
